export const customCategories = [
  {id: 'Caprica', name: 'Caprica', color: '#1DA1F2', icon: '🙃'},
  {id: 'Alarm', name: 'Alarm', color: '#C62168', icon: '⏰'},
  {id: 'Time', name: 'Time', color: '#E15D44', icon: '⏳'},
  {id: 'Summer', name: 'Summer', color: '#ECDB54', icon: '☀️'},
  {
    id: 'Coffee Break',
    name: 'Coffee Break',
    color: '#F9717E',
    icon: '☕️',
  },
  {id: 'Coffee', name: 'Coffee', color: '#F99B20', icon: '☕️'},
  {id: 'Tea Time', name: 'Tea Time', color: '#F3E0BE', icon: '☕️'},
  {id: 'Cardio', name: 'Cardio', color: '#FFD662', icon: '♥️'},
  {id: 'Science', name: 'Science', color: '#F5D6C6', icon: '⚗️'},
  {id: 'Soccer', name: 'Soccer', color: '#5B5EA6', icon: '⚽️'},
  {id: 'Baseball', name: 'Baseball', color: '#6B5B95', icon: '⚾️'},
  {id: 'Winter', name: 'Winter', color: '#D69C2F', icon: '⛄️'},
  {id: 'Church', name: 'Church', color: '#55B4B0', icon: '⛪️'},
  {id: 'Beach', name: 'Beach', color: '#6B5B95', icon: '⛱'},
  {id: 'Golf', name: 'Golf', color: '#343148', icon: '⛳️'},
  {id: 'Sail', name: 'Sail', color: '#FFD662', icon: '⛵️'},
  {id: 'Ski', name: 'Ski', color: '#615550', icon: '⛷'},
  {id: 'Gas', name: 'Gas', color: '#F96714', icon: '⛽️'},
  {id: 'Air Travel', name: 'Air Travel', color: '#88B04B', icon: '✈️'},
  {id: 'Mails', name: 'Mails', color: '#F3E0BE', icon: '✉️'},
  {id: 'Writing', name: 'Writing', color: '#6B5B95', icon: '✍️'},
  {
    id: 'Affirmations',
    name: 'Affirmations',
    color: '#1DA1F2',
    icon: '✓',
  },
  {id: 'Health', name: 'Health', color: '#bada55', icon: '❤️'},
  {id: 'Rainbow', name: 'Rainbow', color: '#55B4B0', icon: '🌈'},
  {id: 'Weather', name: 'Weather', color: '#5B5EA6', icon: '🌤'},
  {id: 'Rain', name: 'Rain', color: '#C0E97A', icon: '🌧'},
  {id: 'Snow', name: 'Snow', color: '#92AE40', icon: '🌨'},
  {id: 'Taco', name: 'Taco', color: '#EAE44F', icon: '🌮'},
  {id: 'Flowers', name: 'Flowers', color: '#D69C2F', icon: '🌺'},
  {id: 'Luck', name: 'Luck', color: '#77212E', icon: '🍀'},
  {id: 'Hamburger', name: 'Hamburger', color: '#FE840E', icon: '🍔'},
  {id: 'Fast Food', name: 'Fast Food', color: '#8D9440', icon: '🍔'},
  {id: 'Pizza', name: 'Pizza', color: '#F9717E', icon: '🍕'},
  {id: 'Carb', name: 'Carb', color: '#F3E0BE', icon: '🍚'},
  {id: 'Dinner', name: 'Dinner', color: '#E15D44', icon: '🍛'},
  {id: 'Eat', name: 'Eat', color: '#FA9A85', icon: '🍜'},
  {id: 'Pasta', name: 'Pasta', color: '#264E36', icon: '🍝'},
  {id: 'Bread', name: 'Bread', color: '#C62168', icon: '🍞'},
  {id: 'Fries', name: 'Fries', color: '#C0E97A', icon: '🍟'},
  {id: 'Sea Food', name: 'Sea Food', color: '#F96714', icon: '🍤'},
  {id: 'Ice cream', name: 'Ice cream', color: '#1DA1F2', icon: '🍦'},
  {id: 'Doughnut', name: 'Doughnut', color: '#577284', icon: '🍩'},
  {id: 'Chocolate', name: 'Chocolate', color: '#2A4B7C', icon: '🍫'},
  {id: 'Challenges', name: 'Challenges', color: '#bada55', icon: '🍬'},
  {id: 'Sugar', name: 'Sugar', color: '#CE5B78', icon: '🍭'},
  {id: 'Honey', name: 'Honey', color: '#F9717E', icon: '🍯'},
  {id: 'Cake', name: 'Cake', color: '#935529', icon: '🍰'},
  {id: 'Sushi', name: 'Sushi', color: '#D2C29D', icon: '🍱'},
  {id: 'Food', name: 'Food', color: '#577284', icon: '🍲'},
  {id: 'Breakfast', name: 'Breakfast', color: '#55B4B0', icon: '🍳'},
  {id: 'Wine', name: 'Wine', color: '#EFC050', icon: '🍷'},
  {id: 'Party', name: 'Party', color: '#F00A48', icon: '🍸'},
  {id: 'Cocktail', name: 'Cocktail', color: '#17BF63', icon: '🍹'},
  {id: 'Beer', name: 'Beer', color: '#F5D6C6', icon: '🍺'},
  {id: 'Hangout', name: 'Hangout', color: '#2A293E', icon: '🍻'},
  {id: 'Baby Care', name: 'Baby Care', color: '#B565A7', icon: '🍼'},
  {id: 'Movies', name: 'Movies', color: '#8D9440', icon: '🍿'},
  {id: 'Netflix', name: 'Netflix', color: '#EA6262', icon: '🍿'},
  {id: 'Gift', name: 'Gift', color: '#009B77', icon: '🎁'},
  {id: 'Halloween', name: 'Halloween', color: '#D65076', icon: '🎃'},
  {id: 'Christmas', name: 'Christmas', color: '#F1EA7F', icon: '🎄'},
  {id: 'Festival', name: 'Festival', color: '#E08119', icon: '🎊'},
  {id: 'Décor', name: 'Décor', color: '#F5D6C6', icon: '🎍'},
  {id: 'Remember', name: 'Remember', color: '#343148', icon: '🎗'},
  {id: 'Reminder', name: 'Reminder', color: '#B565A7', icon: '🎗'},
  {id: 'Podcasts', name: 'Podcasts', color: '#D65076', icon: '🎙'},
  {id: 'Fishing', name: 'Fishing', color: '#C0E97A', icon: '🎣'},
  {id: 'Sing', name: 'Sing', color: '#6B5B95', icon: '🎤'},
  {id: 'Karaoke', name: 'Karaoke', color: '#17BF63', icon: '🎤'},
  {id: 'Music', name: 'Music', color: '#FFD662', icon: '🎧'},
  {id: 'Paint', name: 'Paint', color: '#FFD662', icon: '🎨'},
  {
    id: 'Performing Art',
    name: 'Performing Art',
    color: '#bada55',
    icon: '🎭',
  },
  {id: 'Opera', name: 'Opera', color: '#ECDB54', icon: '🎭'},
  {id: 'Game', name: 'Game', color: '#264E36', icon: '🎮'},
  {id: 'Bad Luck', name: 'Bad Luck', color: '#F00A48', icon: '🎱'},
  {id: 'Bowling', name: 'Bowling', color: '#FF5A61', icon: '🎳'},
  {id: 'Concert', name: 'Concert', color: '#C3447A', icon: '🎸'},
  {id: 'Tennis', name: 'Tennis', color: '#92A8D1', icon: '🎾'},
  {id: 'Basketball', name: 'Basketball', color: '#ECDB54', icon: '🏀'},
  {id: 'Running', name: 'Running', color: '#1DA1F2', icon: '🏃‍♀️'},
  {id: 'HIIT', name: 'HIIT', color: '#955251', icon: '🏃‍♂️'},
  {id: 'Surf', name: 'Surf', color: '#45B8AC', icon: '🏄‍♂️'},
  {id: 'Trophy', name: 'Trophy', color: '#955251', icon: '🏆'},
  {id: 'Racing', name: 'Racing', color: '#C0E97A', icon: '🏇'},
  {id: 'Football', name: 'Football', color: '#E8B5CE', icon: '🏈'},
  {id: 'Swimming', name: 'Swimming', color: '#83C3FF', icon: '🏊‍♂️'},
  {id: 'Workout', name: 'Workout', color: '#C3447A', icon: '🏋️‍♂️'},
  {
    id: 'Weight Lifting',
    name: 'Weight Lifting',
    color: '#615550',
    icon: '🏋️‍♂️',
  },
  {id: 'Bike', name: 'Bike', color: '#B565A7', icon: '🏍'},
  {id: 'Cricket', name: 'Cricket', color: '#88B04B', icon: '🏏'},
  {id: 'Ice Hockey', name: 'Ice Hockey', color: '#92A8D1', icon: '🏒'},
  {id: 'Camping', name: 'Camping', color: '#F1EA7F', icon: '🏕'},
  {id: 'Vacation', name: 'Vacation', color: '#F9717E', icon: '🏖'},
  {id: 'Holiday', name: 'Holiday', color: '#F7CAC9', icon: '🏝'},
  {id: 'Dreams', name: 'Dreams', color: '#77212E', icon: '🏞'},
  {id: 'Home', name: 'Home', color: '#55B4B0', icon: '🏡'},
  {id: 'Office', name: 'Office', color: '#577284', icon: '🏣'},
  {id: 'Finance', name: 'Finance', color: '#2A4B7C', icon: '🏦'},
  {id: 'Hotel', name: 'Hotel', color: '#7FCDCD', icon: '🏨'},
  {id: 'School', name: 'School', color: '#BC70A4', icon: '🏫'},
  {id: 'Label', name: 'Label', color: '#5B5EA6', icon: '🏷'},
  {id: 'Archery', name: 'Archery', color: '#92AE40', icon: '🏹'},
  {id: 'Sheeps', name: 'Sheeps', color: '#6B5B95', icon: '🐑'},
  {id: 'Sit', name: 'Sit', color: '#C3447A', icon: '🐒'},
  {id: 'Pet', name: 'Pet', color: '#C0E97A', icon: '🐶'},
  {id: 'Eye Twitch', name: 'Eye Twitch', color: '#CE5B78', icon: '👀'},
  {id: 'Thumbs Up', name: 'Thumbs Up', color: '#FF5A61', icon: '👍'},
  {id: 'Fashion', name: 'Fashion', color: '#F7CAC9', icon: '👗'},
  {id: 'Sunbath', name: 'Sunbath', color: '#F3DE39', icon: '👙'},
  {id: 'Solarium', name: 'Solarium', color: '#F3DE39', icon: '👙'},
  {id: 'Steps', name: 'Steps', color: '#C0E97A', icon: '👣'},
  {
    id: 'Doctor Check',
    name: 'Doctor Check',
    color: '#5B5EA6',
    icon: '👨‍⚕️',
  },
  {id: 'Lecture', name: 'Lecture', color: '#F5D6C6', icon: '👨‍🏫'},
  {id: 'Family', name: 'Family', color: '#F96714', icon: '👨‍👩‍👧'},
  {id: 'Dentist', name: 'Dentist', color: '#6B5B95', icon: '👩‍⚕️'},
  {id: 'Date', name: 'Date', color: '#17BF63', icon: '👩‍❤️‍💋‍👨'},
  {id: 'Cooking', name: 'Cooking', color: '#bada55', icon: '👩‍🍳'},
  {id: 'Study', name: 'Study', color: '#EFC050', icon: '👩‍🎓'},
  {id: 'Art', name: 'Art', color: '#92A8D1', icon: '👩‍🎨'},
  {id: 'Education', name: 'Education', color: '#EFC050', icon: '👩‍🏫'},
  {id: 'Business', name: 'Business', color: '#C0E97A', icon: '👩‍💼'},
  {id: 'Personal', name: 'Personal', color: '#FF5A61', icon: '👩‍🦳'},
  {id: 'Girls Night', name: 'Girls Night', color: '#4A5FE1', icon: '👯‍♀️'},
  {id: 'Wedding', name: 'Wedding', color: '#EAE44F', icon: '👰'},
  {id: 'Aliens', name: 'Aliens', color: '#F9717E', icon: '👽'},
  {id: 'Evil', name: 'Evil', color: '#D65076', icon: '💀'},
  {id: 'Hair', name: 'Hair', color: '#F3E0BE', icon: '💁‍♀️'},
  {id: 'Dance', name: 'Dance', color: '#D65076', icon: '💃'},
  {id: 'Makeup', name: 'Makeup', color: '#EAE44F', icon: '💄'},
  {id: 'Nais', name: 'Nais', color: '#755139', icon: '💅'},
  {id: 'Nail Care', name: 'Nail Care', color: '#FF6F61', icon: '💅'},
  {id: 'Massage', name: 'Massage', color: '#FF6F61', icon: '💆‍♀️'},
  {id: 'Hair Cut', name: 'Hair Cut', color: '#616247', icon: '💇🏼‍♀️'},
  {id: 'Needle', name: 'Needle', color: '#F99B20', icon: '💉'},
  {id: 'Medicine', name: 'Medicine', color: '#F9717E', icon: '💉'},
  {id: 'Medication', name: 'Medication', color: '#C0E97A', icon: '💊'},
  {id: 'Pills', name: 'Pills', color: '#6B5B95', icon: '💊'},
  {id: 'Beauty', name: 'Beauty', color: '#F1EA7F', icon: '💋'},
  {id: 'Love', name: 'Love', color: '#F99B20', icon: '💌'},
  {id: 'Special', name: 'Special', color: '#1DA1F2', icon: '💍'},
  {id: 'Plant', name: 'Plant', color: '#755139', icon: '💐'},
  {id: 'Water', name: 'Water', color: '#8C7CF2', icon: '💧'},
  {id: 'Fart', name: 'Fart', color: '#88B04B', icon: '💨'},
  {id: 'Poop', name: 'Poop', color: '#F7A5A3', icon: '💩'},
  {
    id: 'Diaper change',
    name: 'Diaper change',
    color: '#F5D6C6',
    icon: '💩',
  },
  {id: 'Fitness', name: 'Fitness', color: '#1DA1F2', icon: '💪'},
  {
    id: 'Personal Opinions',
    name: 'Personal Opinions',
    color: '#343148',
    icon: '💭',
  },
  {id: 'Thought', name: 'Thought', color: '#CE5B78', icon: '💭'},
  {id: 'Credit Card', name: 'Credit Card', color: '#9F9C99', icon: '💳'},
  {id: 'Money', name: 'Money', color: '#FF6F61', icon: '💵'},
  {id: 'Spending', name: 'Spending', color: '#C0E97A', icon: '💸'},
  {id: 'Note', name: 'Note', color: '#F7CAC9', icon: '📒'},
  {id: 'Reading', name: 'Articles', color: '#955251', icon: '📖'},
  {id: 'Homework', name: 'Homework', color: '#bada55', icon: '📚'},
  {id: 'Books', name: 'Books', color: '#B0CB60', icon: '📚'},
  {id: 'Call', name: 'Call', color: '#EAE44F', icon: '📞'},
  {id: 'Package', name: 'Package', color: '#2A293E', icon: '📦'},
  {id: 'Emails', name: 'Emails', color: '#264E36', icon: '📩'},
  {id: 'Apps', name: 'Apps', color: '#F7A5A3', icon: '📱'},
  {id: 'Photoshoot', name: 'Photoshoot', color: '#C0E97A', icon: '📷'},
  {id: 'Recording', name: 'Recording', color: '#C0E97A', icon: '📹'},
  {id: 'TV', name: 'TV', color: '#9F9C99', icon: '📺'},
  {id: 'Video', name: 'Video', color: '#F9717E', icon: '📼'},
  {id: 'Battery', name: 'Battery', color: '#FF6F61', icon: '🔋'},
  {id: 'Lock', name: 'Lock', color: '#E08119', icon: '🔐'},
  {id: 'Coupons', name: 'Coupons', color: '#6B5B95', icon: '🔖'},
  {id: 'Experiment', name: 'Experiment', color: '#FA9A85', icon: '🔬'},
  {id: 'Fortune', name: 'Fortune', color: '#616247', icon: '🔮'},
  // {id: 'Kaaba', name: 'Kaaba', color: '#C0E97A', icon: '🕋'},
  {id: 'Mosque', name: 'Mosque', color: '#45B8AC', icon: '🕌'},
  {id: 'Synagogue', name: 'Synagogue', color: '#92AE40', icon: '🕍'},
  {id: 'Secret', name: 'Secret', color: '#FA9A85', icon: '🕯'},
  {id: 'Archive', name: 'Archive', color: '#2A4B7C', icon: '🗂'},
  {id: 'Tasks', name: 'Tasks', color: '#264E36', icon: '🗃'},
  {id: 'Travel', name: 'Travel', color: '#2A293E', icon: '🗺'},
  {id: 'Accident', name: 'Accident', color: '#2A4B7C', icon: '🤒'},
  {id: 'Handshake', name: 'Handshake', color: '#D2C29D', icon: '🤝'},
  {
    id: 'People I Meet',
    name: 'People I Meet',
    color: '#F0EAD6',
    icon: '🤝',
  },
  {id: 'Cowboy', name: 'Cowboy', color: '#2A293E', icon: '🤠'},
  {id: 'Ill', name: 'Ill', color: '#1DA1F2', icon: '🤢'},
  {id: 'Shy', name: 'Shy', color: '#F5D6C6', icon: '🤦‍♀️'},
  {id: 'Sneeze', name: 'Sneeze', color: '#F96714', icon: '🤧'},
  {id: 'Shush', name: 'Shush', color: '#92A8D1', icon: '🤫'},
  {id: 'Swear', name: 'Swear', color: '#F1EA7F', icon: '🤬'},
  {id: 'Vomit', name: 'Vomit', color: '#264E36', icon: '🤮'},
  {id: 'Sick', name: 'Sick', color: '#577284', icon: '🤮'},
  {id: 'Mind Care', name: 'Mind Care', color: '#FE840E', icon: '🤯'},
  {
    id: 'Breastfeeding',
    name: 'Breastfeeding',
    color: '#ECDB54',
    icon: '🤱',
  },
  {id: 'Selfie', name: 'Selfie', color: '#E8B5CE', icon: '🤳'},
  {id: 'Pilates', name: 'Pilates', color: '#55B4B0', icon: '🤸‍♂️'},
  {id: 'Diving', name: 'Diving', color: '#343148', icon: '🤿'},
  {id: 'Scuba', name: 'Scuba', color: '#1DA1F2', icon: '🤿'},
  {id: 'Alcohol', name: 'Alcohol', color: '#5B5EA6', icon: '🥃'},
  {id: 'Boxing', name: 'Boxing', color: '#D65076', icon: '🥊'},
  {id: 'Curling', name: 'Curling', color: '#F0EAD6', icon: '🥌'},
  {id: 'Lacrosse', name: 'Lacrosse', color: '#92A8D1', icon: '🥍'},
  {id: 'Diet', name: 'Diet', color: '#F99B20', icon: '🥑'},
  {id: 'Salad', name: 'Salad', color: '#797B3A', icon: '🥗'},
  {id: 'Sandwich', name: 'Sandwich', color: '#DD4132', icon: '🥙'},
  {id: 'Egg', name: 'Egg', color: '#FF6F61', icon: '🥚'},
  {id: 'Milk', name: 'Milk', color: '#77212E', icon: '🥛'},
  {id: 'Fruits', name: 'Fruits', color: '#FFD662', icon: '🥝'},
  {id: 'Hydration', name: 'Hydration', color: '#FF6F61', icon: '🥤'},
  {id: 'Drink', name: 'Drink', color: '#F5D6C6', icon: '🥤'},
  {id: 'Vegetable', name: 'Vegetable', color: '#C0E97A', icon: '🥦'},
  {id: 'Pie', name: 'Pie', color: '#E08119', icon: '🥧'},
  {id: 'Meat', name: 'Meat', color: '#FF6F61', icon: '🥩'},
  {id: 'Protein', name: 'Protein', color: '#FF6F61', icon: '🥩'},
  {id: 'Tired', name: 'Tired', color: '#B565A7', icon: '🥱'},
  {id: 'Birth Day', name: 'Birth Day', color: '#D65076', icon: '🥳'},
  {id: 'Dinosaur', name: 'Dinosaur', color: '#55B4B0', icon: '🦕'},
  {id: 'Dental Care', name: 'Dental Care', color: '#5B5EA6', icon: '🦷'},
  {id: 'Cheese', name: 'Cheese', color: '#17BF63', icon: '🧀'},
  {id: 'Salt', name: 'Salt', color: '#2A293E', icon: '🧂'},
  {id: 'Beverage', name: 'Beverage', color: '#FA9A85', icon: '🧃'},
  {id: 'Weight', name: 'Weight', color: '#C0E97A', icon: '🧍‍♀️'},
  {id: 'Stand Up', name: 'Stand Up', color: '#F9717E', icon: '🧍‍♂️'},
  {id: 'Body Care', name: 'Body Care', color: '#45B8AC', icon: '🧖‍♀️'},
  {id: 'Self Care', name: 'Self Care', color: '#E8B5CE', icon: '🧖‍♀️'},
  {id: 'Climbing', name: 'Climbing', color: '#D69C2F', icon: '🧗‍♂️'},
  {id: 'Meditation', name: 'Meditation', color: '#C0E97A', icon: '🧘‍♀️'},
  {id: 'Yoga', name: 'Yoga', color: '#B5CFFF', icon: '🧘‍♀️'},
  {id: 'Projects', name: 'Projects', color: '#6B5B95', icon: '🧪'},
  {id: 'Skin Care', name: 'Skin Care', color: '#F7A5A3', icon: '🧴'},
  {id: 'Moisturize', name: 'Moisturize', color: '#7FCDCD', icon: '🧴'},
  {id: 'Sewing', name: 'Sewing', color: '#755139', icon: '🧵'},
  {id: 'Toys', name: 'Toys', color: '#D69C2F', icon: '🧸'},
  {id: 'Chore', name: 'Chore', color: '#FFD662', icon: '🧹'},
  {id: 'Clean Up', name: 'Clean Up', color: '#F9717E', icon: '🧹'},
  {id: 'Picnic', name: 'Picnic', color: '#C0E97A', icon: '🧺'},
  {id: 'Wash hands', name: 'Wash hands', color: '#797B3A', icon: '🧼'},
  {id: 'Receipts', name: 'Receipts', color: '#797B3A', icon: '🧾'},
  {id: 'Period', name: 'Period', color: '#F5D6C6', icon: '🩸'},
  {id: 'Shave', name: 'Shave', color: '#E15D44', icon: '🪒'},
  {id: 'Joke', name: 'Joke', color: '#C0E97A', icon: '😂'},
  {id: 'Mood', name: 'Mood', color: '#17BF63', icon: '😇'},
  {id: 'Nailed It', name: 'Nailed It', color: '#FF5A61', icon: '😎'},
  {
    id: 'Disappointed',
    name: 'Disappointed',
    color: '#955251',
    icon: '😔',
  },
  {id: 'Sex', name: 'Sex', color: '#F9717E', icon: '😘'},
  {id: 'Lied', name: 'Lied', color: '#E08119', icon: '😠'},
  {id: 'Anger', name: 'Anger', color: '#935529', icon: '😡'},
  {id: 'Dizzy', name: 'Dizzy', color: '#F3E0BE', icon: '😣'},
  {id: 'Cry', name: 'Cry', color: '#F7A5A3', icon: '😭'},
  {id: 'Pain', name: 'Pain', color: '#616247', icon: '😭'},
  {id: 'Scream', name: 'Scream', color: '#92A8D1', icon: '😱'},
  {id: 'Sleep', name: 'Sleep', color: '#F7DC21', icon: '😴'},
  {id: 'Thinking', name: 'Thinking', color: '#EAE44F', icon: '🙇‍♂️'},
  {id: 'Nerd', name: 'Nerd', color: '#88B04B', icon: '️️🙇‍♂️'},
  {id: 'Pray', name: 'Pray', color: '#5B5EA6', icon: '🙏'},
  {id: 'Driving', name: 'Driving', color: '#C0E97A', icon: '🚙'},
  {id: 'Door', name: 'Door', color: '#92A8D1', icon: '🚪'},
  {id: 'Smoke', name: 'Smoke', color: '#C0E97A', icon: '🚬'},
  {id: 'Cigarette', name: 'Cigarette', color: '#EAE44F', icon: '🚬'},
  {id: 'Drink Water', name: 'Drink Water', color: '#8C7CF2', icon: '🚰'},
  {id: 'Cycling', name: 'Cycling', color: '#FF6F61', icon: '🚵‍♂️'},
  {id: 'WC', name: 'WC', color: '#EAE44F', icon: '🚽'},
  {id: 'Shower', name: 'Shower', color: '#99CFFF', icon: '🚿'},
  {id: 'Bath', name: 'Bath', color: '#83AEFF', icon: '🛀'},
  {id: 'Lay down', name: 'Lay down', color: '#6B5B95', icon: '🛋'},
  {id: 'Resting', name: 'Resting', color: '#F0EAD6', icon: '🛌'},
  {id: 'Shopping', name: 'Shopping', color: '#1DA1F2', icon: '🛍'},
  {id: 'Grocery', name: 'Grocery', color: '#bada55', icon: '🛒'},
  {id: 'Maintenance', name: 'Maintenance', color: '#FFD662', icon: '🛠'},
  {id: 'Ship', name: 'Ship', color: '#F7A5A3', icon: '🛳'},
  {id: 'Scooter', name: 'Scooter', color: '#C0AB8E', icon: '🛴'},
  {id: 'Skate', name: 'Skate', color: '#55B4B0', icon: '🛹'},
  {id: 'Decease', name: 'Decease', color: '#EFC050', icon: '⚰️'},
  {id: 'Funeral', name: 'Funeral', color: '#45B8AC', icon: '⚱️'},
];
